import Image from "next/image";

export default function ScrollingIcons() {
    return (
        <div className="icons-container flex flex-col w-[100%] md:max-w-[45rem] backdrop-blur-3xl bg-mywhite/50 dark:bg-myblack/50 z-40">
            <div className="flex flex-row scrolling-icons forward">
                <Image
                    src="/icons/icons_light/whatsapp_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/email_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/arc_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/to_do_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/messages_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/crossy_road_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/slack_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/clock_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/safari_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/maps_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/letterboxd_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/app_store_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />

                <Image
                    src="/icons/icons_light/whatsapp_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/email_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/arc_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/to_do_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/messages_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/crossy_road_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/slack_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/clock_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/safari_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/maps_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/letterboxd_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/app_store_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
            </div>

            <div className="flex flex-row scrolling-icons backward">
                <Image
                    src="/icons/icons_dark/spotify_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/phone_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/letterboxd_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/netflix_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/settings_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/clock_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/health_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/to_do_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/chrome_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/youtube_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/clock_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/slack_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />

                <Image
                    src="/icons/icons_dark/spotify_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/phone_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/letterboxd_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/netflix_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/settings_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/clock_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/health_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/to_do_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/chrome_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/youtube_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/clock_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/slack_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
            </div>

            <div className="flex flex-row scrolling-icons forward">
                <Image
                    src="/icons/icons_light/app_store_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/arc_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/disney+_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/canvas_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/maps_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/whatsapp_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/email_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/netflix_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/health_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/messages_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/spotify_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/instagram_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />

                <Image
                    src="/icons/icons_light/app_store_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/arc_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/disney+_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/canvas_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/maps_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/whatsapp_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/email_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/netflix_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/health_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/messages_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/spotify_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/instagram_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
            </div>

            <div className="flex flex-row scrolling-icons backward">
                <Image
                    src="/icons/icons_dark/youtube_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/chrome_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/slack_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/crossy_road_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/safari_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/instagram_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/phone_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/canvas_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/disney+_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/settings_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/canvas_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/disney+_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />

                <Image
                    src="/icons/icons_dark/youtube_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/chrome_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/slack_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/crossy_road_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/safari_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/instagram_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/phone_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/canvas_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/disney+_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/settings_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_dark/canvas_dark.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
                <Image
                    src="/icons/icons_light/disney+_light.jpg"
                    alt=""
                    width={75}
                    height={75}
                    className="scrolling-icon"
                />
            </div>
        </div>
    );
}
